- hosts: Webserver
  tasks:
  - name: Instalando o phyton3, virtual env
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Git Clone
    ansible.builtin.git:
      repo: https://github.com/alura-cursos/clientes-leo-api.git
      dest: /home/ubuntu/test
      version: master
      force: yes
  - name: Instalando dependencias com PIP (Django e Django rest)
    pip:
      virtualenv: /home/ubuntu/test/virtualenv
      requirements: /home/ubuntu/test/requirements.txt

  - name: Alterando o hosts do settings 
    lineinfile:
      path: /home/ubuntu/test/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
  - name: Configurando banco de dados
    shell: '. /home/ubuntu/test/virtualenv/bin/activate; python /home/ubuntu/test/manage.py migrate'
  - name: Carregando dados iniciais
    shell: '. /home/ubuntu/test/virtualenv/bin/activate; python /home/ubuntu/test/manage.py loaddata clientes.json'
  - name: Start de servidor
    shell: '. /home/ubuntu/test/virtualenv/bin/activate;  nohup python /home/ubuntu/test/manage.py runserver 0.0.0.0:8080 &'     