- hosts: Webserver
  tasks:
  - name: Instalando o phyton3, virtual env
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Instalando dependencias com PIP (Django e Django rest)
    pip:
      virtualenv: /home/ubuntu/test/virtualenv
      name:
        - django
        - djangorestframework
  - name: Iniciando o projeto
    shell: '. /home/ubuntu/test/virtualenv/bin/activate; django-admin startproject setup /home/ubuntu/test'
  - name: Alterando o hosts do settings 
    lineinfile:
      path: /home/ubuntu/test/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
      